'use client';

import React, { useState, useEffect, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import { 
  Sparkles, 
  ArrowRight, 
  Tv, 
  Smartphone, 
  Globe, 
  PartyPopper,
  ExternalLink,
  ShieldAlert,
  Loader2,
  Wand2,
  Building2,
  Dumbbell,
  Utensils,
  Home,
  Stethoscope,
  Briefcase,
  ShoppingBag,
  GraduationCap,
  MessageCircle,
  Check,
  Star,
  ShieldCheck,
  MapPin,
  Phone,
  Layout,
  ArrowLeft,
  MousePointer2,
  CheckCircle
} from 'lucide-react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';

// Business Type Presets
const businessTypes = [
  { id: 'Salon', name: 'Salon / Spa', icon: Building2, desc: 'Hair, beauty & wellness studios' },
  { id: 'Gym', name: 'Gym / Fitness', icon: Dumbbell, desc: 'Fitness centers, yoga & trainers' },
  { id: 'Restaurant', name: 'Restaurant / Cafe', icon: Utensils, desc: 'Cafes, dining & cloud kitchens' },
  { id: 'Real Estate', name: 'Real Estate', icon: Home, desc: 'Properties, agents & builders' },
  { id: 'Doctor', name: 'Clinic / Doctor', icon: Stethoscope, desc: 'Dental, medical & clinics' },
  { id: 'Agency', name: 'Agency / IT', icon: Briefcase, desc: 'Marketing, design & services' },
  { id: 'Ecommerce', name: 'D2C / Store', icon: ShoppingBag, desc: 'Fashion, gadgets & products' },
  { id: 'Education', name: 'Tutor / Coaching', icon: GraduationCap, desc: 'Online classes & institutes' },
];

export default function HybridWebsiteBuilder() {
  // Navigation Screens: 1 = Type Select, 2 = Conversational Info, 3 = AI Processing, 4 = Live Preview Editor
  const [currentScreen, setCurrentScreen] = useState(1);
  const [formStep, setFormStep] = useState(0); // 0 = GMB or Manual Choice, 1-5 = Conversational Questions

  // Form Fields State
  const [businessType, setBusinessType] = useState('Salon');
  const [businessName, setBusinessName] = useState('');
  const [tagline, setTagline] = useState('');
  const [whatsapp, setWhatsapp] = useState('');
  const [address, setAddress] = useState('');
  const [servicesInput, setServicesInput] = useState('');
  const [theme, setTheme] = useState('orange');
  const [aboutText, setAboutText] = useState('');
  const [subdomain, setSubdomain] = useState('');

  // AI Prompt Autofill State
  const [aiPrompt, setAiPrompt] = useState('');
  const [isAutofilling, setIsAutofilling] = useState(false);

  // Enhanced Content State (Generated by AI Engine)
  const [enhancedData, setEnhancedData] = useState({
    heroTitle: 'Transform Your Style With Premium Salon Experience',
    heroDescription: 'Experience luxury styling, professional grooming, and personalized care delivered by certified experts.',
    ctaText: 'Book VIP Appointment',
    aboutHeadline: 'Excellence in Every Detail',
    aboutBody: 'Established with a passion for unmatched personal care, we bring world-class techniques directly to your neighborhood.',
    stats: [
      { label: 'Happy Clients', value: '1000+' },
      { label: 'Years Experience', value: '12+' },
      { label: 'Success Rate', value: '100%' }
    ],
    features: [
      { title: 'Verified Pros', desc: 'Background checked and certified experts.' },
      { title: 'Modern Tools', desc: 'Using the latest technology for best results.' },
      { title: 'Secure Service', desc: 'Your safety and satisfaction is our priority.' }
    ],
    servicesList: [
      { name: 'Precision Hair Styling', desc: 'Custom styling tailored to your unique profile.' },
      { name: 'Advanced Skin Care', desc: 'Rejuvenating therapies using premium ingredients.' },
      { name: 'Bridal & Makeovers', desc: 'Flawless preparation for your important occasions.' }
    ],
    testimonials: [
      { name: 'Priya Sharma', review: 'Best service in town! Totally transformed my look.' },
      { name: 'Rahul Verma', review: 'Extremely professional staff and top hygiene standards.' }
    ],
    faqs: [
      { q: 'How can I book an appointment?', a: 'Click the WhatsApp button to chat directly with our team.' },
      { q: 'Where are you located?', a: 'We are situated centrally. Click View Location for directions.' }
    ]
  });

  // Preview / Publish States
  const [previewMode, setPreviewMode] = useState('desktop');
  const [loading, setLoading] = useState(false);
  const [subdomainError, setSubdomainError] = useState('');
  const [successData, setSuccessData] = useState(null);

  // Subdomain Sanitizer
  const handleSubdomainChange = (e) => {
    const rawVal = e.target.value;
    const cleanVal = rawVal.toLowerCase().replace(/[^a-z0-9]/g, '');
    setSubdomain(cleanVal);
    setSubdomainError('');
  };

  // Step 1 -> Step 2
  const handleSelectType = (typeId) => {
    setBusinessType(typeId);
    setCurrentScreen(2);
    setFormStep(0);
  };

  // Magic AI Prompt Autofill Simulator & Live Backend Scraper
  const handleAiAutofill = async (e) => {
    if (e) e.preventDefault();
    if (!aiPrompt.trim()) return;

    setIsAutofilling(true);
    setCurrentScreen(3); // Show AI Enhancement processing screen

    try {
      const pLower = aiPrompt.toLowerCase();
      const isUrl = pLower.includes('http') || pLower.includes('share.google') || pLower.includes('goo.gl') || pLower.includes('maps.app');

      let bName = businessName || 'Premium Business';
      let bPhone = whatsapp || '919955123456';
      let bAddr = address || 'Bhabua, Bihar';
      let bAbout = aboutText;
      let bTag = tagline;
      let bSrvs = servicesInput ? servicesInput.split(',').map(s => s.trim()) : [];

      if (isUrl) {
        const res = await fetch('/api/scrape-gmb', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: aiPrompt })
        });
        const data = await res.json();

        if (data.success) {
          bName = data.businessName || bName;
          bPhone = data.phone || bPhone;
          bAddr = data.address || bAddr;
          bAbout = `Verified and top-rated ${data.category || 'business'} on Google Maps. ${bName} provides premium quality execution delivered by certified professionals.`;
          setBusinessName(bName);
          setWhatsapp(bPhone);
          setAddress(bAddr);
          setAboutText(bAbout);
          setTheme('blue');
        }
      }

      // Call AI Copywriter
      const copyRes = await fetch('/api/generate-copy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ businessName: bName, businessType, address: bAddr, phone: bPhone, aboutText: bAbout })
      });
      const aiCopy = await copyRes.json();

      setEnhancedData({
        heroTitle: aiCopy.heroTitle || `Transform Your Space With Premium Quality By ${bName}`,
        heroDescription: aiCopy.heroDescription || `Experience top-tier service, professional execution, and dedicated customer satisfaction at ${bName}.`,
        ctaText: 'Chat on WhatsApp',
        aboutHeadline: aiCopy.aboutHeadline || 'Committed to Unmatched Quality',
        aboutBody: aiCopy.aboutBody || bAbout || `Founded with a mission to deliver premium ${businessType} services in ${bAddr}.`,
        businessName: bName,
        phone: bPhone,
        address: bAddr,
        tagline: aiCopy.tagline || bTag || `Best ${businessType} in town`,
        servicesList: aiCopy.servicesList || (bSrvs.length > 0 ? bSrvs.map(s => ({ name: s, desc: `Professional execution of ${s.toLowerCase()}.` })) : []),
        stats: aiCopy.stats || [],
        features: aiCopy.features || [],
        testimonials: aiCopy.testimonials || [
          { name: 'Amit Kumar', review: `Outstanding service from ${bName}! Highly recommended.` },
          { name: 'Sneha Gupta', review: `Very seamless experience and excellent quality.` }
        ],
        faqs: aiCopy.faqs || [
          { q: 'How can I book?', a: `Simply click the WhatsApp button to connect with the ${bName} team.` },
          { q: 'Where are you located?', a: `We are proudly located in ${bAddr}.` }
        ]
      });

      if (!subdomain) {
        setSubdomain(bName.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 15));
      }

    } catch (err) {
      console.error('Scrape/AI Error:', err);
    } finally {
      setIsAutofilling(false);
      setCurrentScreen(4);
    }
  };

  // New Conversational Step Handler
  const nextFormStep = () => {
    if (formStep === 1 && !businessName) return alert('Please enter your business name');
    if (formStep === 2 && !whatsapp) return alert('Please enter your WhatsApp number');
    
    if (formStep < 5) {
      setFormStep(formStep + 1);
    } else {
      handleEnhanceSubmit();
    }
  };

  const prevFormStep = () => {
    if (formStep > 0) setFormStep(formStep - 1);
    else setCurrentScreen(1);
  };

  // Final Submission from Conversational Flow
  const handleEnhanceSubmit = async () => {
    setCurrentScreen(3); // Loading
    
    try {
      const bName = businessName || 'My Business';
      const bAddr = address || 'India';
      const bPhone = whatsapp || '919955123456';
      
      const copyRes = await fetch('/api/generate-copy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          businessName: bName, 
          businessType, 
          address: bAddr, 
          phone: bPhone, 
          aboutText: aboutText || `A professional ${businessType} business dedicated to quality.`
        })
      });
      const aiCopy = await copyRes.json();

      setEnhancedData({
        heroTitle: aiCopy.heroTitle || `Experience Premium ${businessType} With ${bName}`,
        heroDescription: aiCopy.heroDescription || `Get top-quality services from the best professionals in ${bAddr}.`,
        ctaText: 'Chat on WhatsApp',
        aboutHeadline: aiCopy.aboutHeadline || 'Our Story',
        aboutBody: aiCopy.aboutBody || aboutText || `Dedicated to excellence since our inception.`,
        businessName: bName,
        phone: bPhone,
        address: bAddr,
        tagline: aiCopy.tagline || tagline || `Expert ${businessType} Services`,
        servicesList: aiCopy.servicesList || (servicesInput ? servicesInput.split(',').map(s => ({ name: s.trim(), desc: `Expert ${s.trim()} services provided with care.` })) : []),
        stats: aiCopy.stats || [],
        features: aiCopy.features || [],
        testimonials: aiCopy.testimonials || [],
        faqs: aiCopy.faqs || []
      });

      if (!subdomain) {
        setSubdomain(bName.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 15));
      }
      
      setCurrentScreen(4);
    } catch (err) {
      console.error('Enhance Error:', err);
      setCurrentScreen(2);
      setFormStep(5);
    }
  };

  // Generate dynamic raw HTML structure for the real-time iframe preview
  const generatePreviewHTML = () => {
    const themeCSS = {
      orange: {
        gradient: "linear-gradient(to top right, #ea580c, #d97706)",
        text: "#ea580c",
        bgLight: "#fff7ed",
        borderLight: "#ffedd5",
        button: "#ea580c",
        bgGradient: "linear-gradient(to bottom, rgba(234, 88, 12, 0.05), transparent)"
      },
      sage: {
        gradient: "linear-gradient(to top right, #047857, #115e59)",
        text: "#047857",
        bgLight: "#f0fdf4",
        borderLight: "#dcfce7",
        button: "#047857",
        bgGradient: "linear-gradient(to bottom, rgba(4, 120, 87, 0.05), transparent)"
      },
      blue: {
        gradient: "linear-gradient(to top right, #2563eb, #4338ca)",
        text: "#2563eb",
        bgLight: "#eff6ff",
        borderLight: "#dbeafe",
        button: "#2563eb",
        bgGradient: "linear-gradient(to bottom, rgba(37, 99, 235, 0.05), transparent)"
      },
      purple: {
        gradient: "linear-gradient(to top right, #9333ea, #c026d3)",
        text: "#9333ea",
        bgLight: "#faf5ff",
        borderLight: "#f3e8ff",
        button: "#9333ea",
        bgGradient: "linear-gradient(to bottom, rgba(147, 51, 234, 0.05), transparent)"
      }
    };

    const activeTheme = themeCSS[theme] || themeCSS.orange;
    const pName = enhancedData.businessName || businessName || 'My Business';
    const pPhone = enhancedData.phone || whatsapp || '919955123456';
    const pAddress = enhancedData.address || address || 'Patel Chowk, Bhabua, Bihar';
    const pTagline = enhancedData.tagline || tagline || 'Premium Services';

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/lucide@latest"></script>
        <style>
          body { font-family: 'Outfit', sans-serif; background-color: #fcfcfc; color: #1c1917; }
        </style>
      </head>
      <body class="min-h-screen flex flex-col justify-between selection:bg-orange-100 antialiased overflow-x-hidden">
        
        <!-- Mesh Backgrounds -->
        <div style="background: ${activeTheme.gradient}; opacity: 0.04; filter: blur(100px);" class="fixed top-0 right-0 w-80 h-80 rounded-full -z-10"></div>
        <div style="background: ${activeTheme.gradient}; opacity: 0.02; filter: blur(80px);" class="fixed bottom-0 left-0 w-60 h-60 rounded-full -z-10"></div>

        <div>
          <header class="border-b border-stone-100 bg-white/70 backdrop-blur-xl sticky top-0 z-50">
            <div class="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
              <div class="flex items-center gap-2.5">
                <div style="background: ${activeTheme.gradient};" class="w-8 h-8 rounded-[10px] flex items-center justify-center text-white font-bold text-xs shadow-lg">
                  ${pName.charAt(0)}
                </div>
                <span class="font-semibold text-base tracking-tight text-stone-950">${pName}</span>
              </div>
              <a href="tel:${pPhone}" class="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-[10px] font-bold uppercase tracking-widest transition hover:opacity-90 shadow-sm border" style="background-color: ${activeTheme.bgLight}; color: ${activeTheme.text}; border-color: ${activeTheme.borderLight};">
                <i data-lucide="phone" style="width:12px; height:12px;"></i> Call
              </a>
            </div>
          </header>

          <section class="pt-16 pb-12 text-center max-w-4xl mx-auto px-6">
            <div class="inline-flex items-center gap-2 px-5 py-2 rounded-full border mb-8 shadow-sm bg-white" style="border-color: #f5f5f4;">
              <div class="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></div>
              <span class="text-[10px] font-bold tracking-widest uppercase text-stone-400">ACTIVE & VERIFIED</span>
            </div>
            <h1 class="text-4xl sm:text-6xl font-semibold text-stone-950 tracking-tight leading-[1.05] mb-8">
              ${enhancedData.heroTitle || `Experience Premium Services`}
            </h1>
            <p class="text-base sm:text-lg text-stone-500 max-w-xl mx-auto leading-relaxed font-medium">
              ${enhancedData.heroDescription || `Providing world-class professional solutions tailored to your needs.`}
            </p>

            <div class="mt-12 flex flex-col sm:flex-row items-center justify-center gap-4">
              <a href="https://wa.me/${pPhone}" target="_blank" class="w-full sm:w-auto inline-flex items-center justify-center gap-3 rounded-full text-white px-10 py-5 text-xs font-bold uppercase tracking-widest transition-all duration-500 shadow-2xl hover:-translate-y-1" style="background-color: ${activeTheme.button};">
                <i data-lucide="message-circle" style="width:18px; height:18px;"></i> Get Quote
              </a>
            </div>

            <div class="mt-12 flex items-center justify-center gap-8">
              <div class="flex items-center gap-2">
                 <div class="flex gap-0.5 text-amber-500">
                    <i data-lucide="star" style="width:10px; height:10px; fill:currentColor;"></i>
                    <i data-lucide="star" style="width:10px; height:10px; fill:currentColor;"></i>
                    <i data-lucide="star" style="width:10px; height:10px; fill:currentColor;"></i>
                    <i data-lucide="star" style="width:10px; height:10px; fill:currentColor;"></i>
                    <i data-lucide="star" style="width:10px; height:10px; fill:currentColor;"></i>
                 </div>
                 <span class="text-[9px] font-bold text-stone-400 uppercase tracking-widest">5.0 Rating</span>
              </div>
              <div class="w-px h-3 bg-stone-200"></div>
              <div class="flex items-center gap-2">
                 <i data-lucide="shield-check" style="width:12px; height:12px;" class="text-emerald-500"></i>
                 <span class="text-[9px] font-bold text-stone-400 uppercase tracking-widest">Secure</span>
              </div>
            </div>
          </section>
        </div>

        <footer class="bg-stone-950 text-white pt-16 pb-12 px-8 mt-20">
          <div class="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-12">
             <div>
                <div style="background: ${activeTheme.gradient};" class="w-12 h-12 rounded-2xl flex items-center justify-center text-white font-bold text-xl mb-6 shadow-lg">
                  ${pName.charAt(0)}
                </div>
                <h2 class="text-xl font-semibold mb-3 tracking-tight">${pName}</h2>
                <p class="text-xs text-stone-500 leading-relaxed max-w-xs font-medium">Premium professional services delivered with unmatched quality and dedication.</p>
             </div>
             <div class="grid grid-cols-2 gap-8">
                <div>
                  <h4 class="text-[10px] font-bold uppercase tracking-widest text-stone-700 mb-6 text-white/20">Contact</h4>
                  <div class="flex flex-col gap-4 text-xs font-medium text-stone-400">
                    <span class="flex items-center gap-2"><i data-lucide="phone" style="width:12px; height:12px; opacity:0.3;"></i> ${pPhone}</span>
                    <span class="flex items-center gap-2"><i data-lucide="message-circle" style="width:12px; height:12px; opacity:0.3;"></i> WhatsApp</span>
                  </div>
                </div>
                <div>
                  <h4 class="text-[10px] font-bold uppercase tracking-widest text-stone-700 mb-6 text-white/20">Address</h4>
                  <p class="text-xs text-stone-400 leading-relaxed font-medium">${pAddress}</p>
                </div>
             </div>
          </div>
          <div class="max-w-5xl mx-auto mt-16 pt-8 border-t border-white/5 text-center">
             <p class="text-[9px] text-white/10 uppercase tracking-[0.4em] font-bold">Powered by Geetanjali Softwares</p>
          </div>
        </footer>
        <script>
          lucide.createIcons();
        </script>
      </body>
      </html>
    `;
  };

  // Publish / Launch Website function
  const handlePublish = async (e) => {
    if (e) e.preventDefault();
    setLoading(true);
    setSubdomainError('');

    if (!subdomain || subdomain.length < 3) {
      setSubdomainError('Subdomain must be at least 3 characters long.');
      setLoading(false);
      return;
    }

    try {
      const res = await fetch('/api/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          subdomain,
          business_name: businessName,
          tagline: enhancedData.tagline || tagline,
          whatsapp,
          address: enhancedData.address || address,
          theme,
          services: enhancedData.servicesList ? enhancedData.servicesList.map(s => s.name) : ['Consultation', 'Quality Execution'],
          hero_title: enhancedData.heroTitle,
          hero_description: enhancedData.heroDescription,
          about_headline: enhancedData.aboutHeadline,
          about_body: enhancedData.aboutBody,
          services_list: enhancedData.servicesList,
          testimonials: enhancedData.testimonials,
          faqs: enhancedData.faqs,
          stats: enhancedData.stats,
          features: enhancedData.features
        })
      });
      const result = await res.json();

      if (!res.ok || result.error) {
        setSubdomainError(result.error || 'Error publishing website. Please try again.');
      } else {
        const isLocal = window.location.hostname.includes('localhost');
        const liveUrl = isLocal 
          ? `http://${subdomain}.localhost:3000` 
          : `https://${subdomain}.geetanjalisoftwares.in`;

        setSuccessData({
          subdomain,
          businessName,
          url: liveUrl
        });
      }
    } catch (err) {
      console.error('Publish Handler Error:', err);
      setSubdomainError('Network error. Please try again.');
    }
    setLoading(false);
  };

  return (
    <div className="h-screen w-screen overflow-hidden bg-[#fcfcfc] text-stone-900 font-sans flex flex-col selection:bg-orange-100 selection:text-orange-900 relative">
      
      {/* Premium Background Accents */}
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-orange-500/5 blur-[120px] rounded-full pointer-events-none -z-10" />
      <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-purple-500/5 blur-[100px] rounded-full pointer-events-none -z-10" />

      {/* Pristine Minimalist Header */}
      <header className="h-20 border-b border-stone-100 px-6 sm:px-10 flex items-center justify-between shrink-0 bg-white/70 backdrop-blur-xl z-50">
        <Link href="/" className="flex items-center gap-2">
          <img src="/images/logo.jpg" alt="Geetanjali Softwares Logo" className="h-8 w-auto object-contain mix-blend-multiply" />
        </Link>
        <div className="flex items-center gap-6">
           <div className="hidden sm:flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-stone-200 shadow-sm text-[10px] font-bold text-stone-500 uppercase tracking-widest">
              <div className="w-2 h-2 rounded-full bg-orange-500 animate-pulse" />
              AI ENGINE ACTIVE
           </div>
           <Link href="/" className="text-[11px] font-bold text-stone-400 hover:text-stone-900 uppercase tracking-widest transition">Exit Builder</Link>
        </div>
      </header>

      {/* Success Modal */}
      <AnimatePresence>
        {successData && (
          <motion.div 
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-stone-950/40 backdrop-blur-md"
          >
            <motion.div 
              initial={{ scale: 0.95, opacity: 0, y: 20 }} animate={{ scale: 1, opacity: 1, y: 0 }}
              className="bg-white p-10 rounded-[40px] max-w-lg w-full text-center relative shadow-2xl border border-stone-100"
            >
              <div className="w-20 h-20 bg-orange-50 rounded-[24px] flex items-center justify-center mx-auto mb-8 border border-orange-100 shadow-inner">
                <PartyPopper className="text-orange-600" size={32} />
              </div>
              <h2 className="text-3xl font-semibold tracking-tight text-stone-950 leading-tight">Congratulations! 🎉<br/>Your Site is Live.</h2>
              <p className="mt-4 text-base text-stone-500 font-medium">Your business now has a premium digital presence.</p>
              
              <div className="mt-10 bg-stone-50 border border-stone-100 p-6 rounded-[32px] flex items-center justify-between gap-4">
                <div className="text-left overflow-hidden">
                  <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 block mb-1">LIVE WEB LINK</span>
                  <span className="text-sm font-semibold text-orange-600 truncate block">{successData.url}</span>
                </div>
                <a href={successData.url} target="_blank" className="bg-orange-600 text-white p-4 rounded-2xl shadow-xl shadow-orange-600/20 hover:bg-orange-700 transition-all"><ExternalLink size={18} /></a>
              </div>
              <button onClick={() => { setSuccessData(null); setCurrentScreen(1); }} className="mt-10 text-[11px] font-bold text-stone-400 hover:text-stone-900 uppercase tracking-widest transition">Build Another Website</button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <main className="flex-grow flex overflow-hidden p-4 sm:p-8 gap-8">
        
        {/* LEFT SIDE: Wizard / Editor */}
        <div className="w-full lg:w-5/12 bg-white rounded-[40px] shadow-[0_32px_64px_-16px_rgba(0,0,0,0.05)] border border-stone-100 flex flex-col overflow-hidden relative">
          
          {/* Progress Header */}
          <div className="px-10 pt-10 pb-8 border-b border-stone-50 shrink-0 bg-white/50 backdrop-blur-sm sticky top-0 z-10">
            <div className="flex items-center justify-between">
              <div>
                <span className="text-[10px] font-bold text-orange-600 uppercase tracking-[0.3em]">
                  {currentScreen === 1 ? 'START ENGINE' : currentScreen === 2 ? `STEP ${formStep + 1}/6` : 'FINAL POLISH'}
                </span>
                <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-stone-950 mt-3 leading-tight">
                  {currentScreen === 1 && "Select Industry"}
                  {currentScreen === 2 && (
                    formStep === 0 ? "Choose Method" :
                    formStep === 1 ? "Business Name" :
                    formStep === 2 ? "Contact Number" :
                    formStep === 3 ? "Your Location" :
                    formStep === 4 ? "Core Services" :
                    "Brand Theme"
                  )}
                  {currentScreen === 3 && "AI Magic..."}
                  {currentScreen === 4 && "Editor"}
                </h2>
              </div>
              {currentScreen > 1 && !successData && (
                <button onClick={prevFormStep} className="p-3.5 rounded-2xl bg-stone-50 border border-stone-100 text-stone-400 hover:text-stone-900 transition-all hover:-translate-x-1"><ArrowLeft size={18} /></button>
              )}
            </div>
          </div>

          <div className="flex-grow overflow-y-auto scrollbar-hide px-10 py-10">
            <AnimatePresence mode="wait">
              
              {/* SCREEN 1: Type Selection */}
              {currentScreen === 1 && (
                <motion.div key="s1" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="grid grid-cols-2 gap-4 pb-6">
                  {businessTypes.map(t => (
                    <button 
                      key={t.id} onClick={() => handleSelectType(t.id)} 
                      className="group text-left p-6 rounded-[32px] border border-stone-100 bg-stone-50 hover:bg-white hover:border-orange-200 transition-all duration-500 hover:-translate-y-1 hover:shadow-xl hover:shadow-orange-900/5"
                    >
                      <div className="w-12 h-12 rounded-2xl bg-white text-orange-600 flex items-center justify-center transition-all duration-500 mb-6 shadow-sm group-hover:bg-orange-600 group-hover:text-white">
                        <t.icon size={22} />
                      </div>
                      <span className="text-sm font-semibold text-stone-950 block leading-tight">{t.name}</span>
                      <p className="text-[11px] text-stone-400 mt-2 leading-relaxed font-medium">{t.desc}</p>
                    </button>
                  ))}
                </motion.div>
              )}

              {/* SCREEN 2: Conversational Steps */}
              {currentScreen === 2 && (
                <motion.div key={`step-${formStep}`} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="space-y-10">
                  
                  {/* STEP 0: Choice (GMB vs Manual) */}
                  {formStep === 0 && (
                    <div className="space-y-6">
                      <div className="p-10 rounded-[40px] bg-stone-950 text-white shadow-2xl relative overflow-hidden group cursor-pointer" onClick={() => setFormStep(1)}>
                         <Sparkles className="absolute -right-6 -bottom-6 w-32 h-32 text-white/5 group-hover:scale-110 transition-transform duration-700" />
                         <div className="relative z-10">
                            <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-white/40 block mb-4">RECOMMENDED</span>
                            <h3 className="text-3xl font-semibold mb-4 tracking-tight leading-tight">Manual AI<br/>Optimization</h3>
                            <p className="text-sm text-white/60 leading-relaxed max-w-[240px] font-medium">Answer 5 simple questions. Our AI handles the premium copywriting and SEO.</p>
                            <div className="mt-8 inline-flex items-center gap-3 text-[11px] font-bold bg-white/10 px-6 py-3 rounded-full hover:bg-white hover:text-stone-950 transition-colors">Start Now <ArrowRight size={14} /></div>
                         </div>
                      </div>

                      <div className="p-10 rounded-[40px] border border-stone-100 bg-stone-50 hover:bg-white transition-all duration-500">
                        <div className="flex items-center gap-3 mb-8">
                          <div className="p-3.5 rounded-2xl bg-white text-stone-900 shadow-sm border border-stone-100"><Globe size={20} /></div>
                          <span className="text-sm font-semibold text-stone-950 tracking-tight">Import from Google Maps</span>
                        </div>
                        <input 
                          type="text" placeholder="Paste GMB Link..." 
                          value={aiPrompt} onChange={(e) => setAiPrompt(e.target.value)}
                          className="w-full bg-white border border-stone-100 rounded-2xl px-6 py-4 text-sm font-medium focus:outline-none focus:border-stone-900 transition-all mb-4 shadow-sm"
                        />
                        <button 
                          onClick={handleAiAutofill} disabled={!aiPrompt}
                          className="w-full py-4 rounded-2xl bg-stone-950 text-white text-[11px] font-bold uppercase tracking-widest disabled:bg-stone-50 disabled:text-stone-300 transition-all active:scale-[0.98] shadow-lg"
                        >Sync Details</button>
                      </div>
                    </div>
                  )}

                  {/* STEP 1: Name */}
                  {formStep === 1 && (
                    <div className="space-y-6">
                      <p className="text-base text-stone-500 font-medium tracking-tight">What should we call your beautiful new website?</p>
                      <input 
                        autoFocus type="text" placeholder="e.g. Akash Electricals" 
                        value={businessName} onChange={(e) => setBusinessName(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && nextFormStep()}
                        className="w-full bg-transparent border-b border-stone-200 py-6 text-2xl sm:text-4xl font-semibold text-stone-950 focus:outline-none focus:border-orange-600 transition-all"
                      />
                    </div>
                  )}

                  {/* STEP 2: WhatsApp */}
                  {formStep === 2 && (
                    <div className="space-y-6">
                      <p className="text-base text-stone-500 font-medium tracking-tight">Where should customers contact you? (WhatsApp)</p>
                      <div className="flex items-center gap-4 bg-stone-50 rounded-[32px] px-8 py-6 border border-stone-100 focus-within:bg-white focus-within:border-stone-900 transition-all">
                        <Phone size={24} className="text-stone-300" />
                        <input 
                          autoFocus type="tel" placeholder="91 9955XX XXXX" 
                          value={whatsapp} onChange={(e) => setWhatsapp(e.target.value)}
                          onKeyDown={(e) => e.key === 'Enter' && nextFormStep()}
                          className="w-full bg-transparent text-2xl font-semibold focus:outline-none placeholder:text-stone-300"
                        />
                      </div>
                    </div>
                  )}

                  {/* STEP 3: Location */}
                  {formStep === 3 && (
                    <div className="space-y-6">
                      <p className="text-base text-stone-500 font-medium tracking-tight">In which city is your business located?</p>
                      <div className="flex items-center gap-4 bg-stone-50 rounded-[32px] px-8 py-6 border border-stone-100 focus-within:bg-white focus-within:border-stone-900 transition-all">
                        <MapPin size={24} className="text-stone-300" />
                        <input 
                          autoFocus type="text" placeholder="e.g. Bhabua, Kaimur" 
                          value={address} onChange={(e) => setAddress(e.target.value)}
                          onKeyDown={(e) => e.key === 'Enter' && nextFormStep()}
                          className="w-full bg-transparent text-2xl font-semibold focus:outline-none placeholder:text-stone-300"
                        />
                      </div>
                    </div>
                  )}

                  {/* STEP 4: Services */}
                  {formStep === 4 && (
                    <div className="space-y-6">
                      <p className="text-base text-stone-500 font-medium tracking-tight">List your main services (comma separated)</p>
                      <textarea 
                        autoFocus rows={4} placeholder="e.g. House Wiring, Inverter Repair, AC Service" 
                        value={servicesInput} onChange={(e) => setServicesInput(e.target.value)}
                        className="w-full bg-stone-50 rounded-[32px] p-8 border border-stone-100 text-xl font-semibold focus:outline-none focus:border-stone-900 focus:bg-white transition-all resize-none shadow-sm"
                      />
                    </div>
                  )}

                  {/* STEP 5: Theme */}
                  {formStep === 5 && (
                    <div className="space-y-8">
                      <p className="text-base text-stone-500 font-medium tracking-tight">Choose your brand's primary color</p>
                      <div className="grid grid-cols-2 gap-4">
                        {[
                          { id: 'orange', name: 'Premium Orange', bg: 'bg-orange-600' },
                          { id: 'blue', name: 'Professional Blue', bg: 'bg-blue-600' },
                          { id: 'sage', name: 'Modern Sage', bg: 'bg-emerald-700' },
                          { id: 'purple', name: 'Creative Purple', bg: 'bg-purple-600' }
                        ].map(t => (
                          <button key={t.id} onClick={() => setTheme(t.id)} className={`p-6 rounded-[32px] border-2 flex flex-col gap-4 transition-all ${theme === t.id ? 'border-orange-600 bg-orange-50 shadow-lg' : 'border-stone-100 bg-white hover:border-stone-200'}`}>
                            <div className={`w-8 h-8 rounded-full ${t.bg} shadow-lg`} />
                            <span className="text-[11px] font-bold uppercase tracking-widest">{t.name}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Bottom Navigation */}
                  {formStep > 0 && (
                    <div className="pt-10">
                       <button 
                        onClick={nextFormStep}
                        className="group w-full py-5 rounded-[32px] bg-orange-600 text-white text-sm font-bold flex items-center justify-center gap-2 shadow-2xl shadow-orange-600/30 hover:bg-orange-700 hover:-translate-y-1 active:scale-95 transition-all"
                       >
                         {formStep === 5 ? "GENERATE PREMIUM SITE ✨" : "NEXT QUESTION"}
                         <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                       </button>
                       
                       {/* Progress bar */}
                       <div className="mt-12 flex gap-2 h-1 px-2">
                          {[1,2,3,4,5].map(i => (
                            <div key={i} className={`flex-grow rounded-full transition-all duration-700 ${i <= formStep ? 'bg-orange-600' : 'bg-stone-100'}`} />
                          ))}
                       </div>
                    </div>
                  )}

                </motion.div>
              )}

              {/* SCREEN 3: Loading */}
              {currentScreen === 3 && (
                <div className="py-24 flex flex-col items-center justify-center text-center">
                  <div className="relative mb-10">
                    <div className="w-24 h-24 bg-orange-50 rounded-[32px] flex items-center justify-center border border-orange-100 shadow-inner">
                      <Wand2 className="text-orange-600 animate-spin" size={36} />
                    </div>
                    <Sparkles className="absolute -top-3 -right-3 text-orange-400 animate-pulse" size={28} />
                  </div>
                  <h3 className="text-2xl font-semibold text-stone-950 tracking-tight">AI Engine is Processing</h3>
                  <p className="mt-4 text-sm text-stone-500 max-w-[280px] leading-relaxed font-medium">Crafting premium headlines, services, and SEO configurations tailored for your brand.</p>
                </div>
              )}

              {/* SCREEN 4: Editor */}
              {currentScreen === 4 && !successData && (
                <motion.div key="s4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-8 pb-20">
                  <div className="p-6 bg-emerald-50 border border-emerald-100 rounded-[32px] text-[11px] font-bold text-emerald-700 flex items-center gap-4">
                    <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center shadow-sm shrink-0">
                      <CheckCircle className="text-emerald-500" size={18} />
                    </div>
                    <span>AI has optimized your business profile for high conversion! Review the details below.</span>
                  </div>

                  <div className="space-y-8">
                    <div className="p-8 bg-stone-50 rounded-[40px] border border-stone-100 space-y-6">
                      <div className="space-y-2">
                        <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 ml-4">YOUR WEB ADDRESS</label>
                        <div className="flex rounded-[24px] border border-stone-200 bg-white px-6 py-4 items-center shadow-sm focus-within:border-stone-900 transition-all">
                          <input value={subdomain} onChange={handleSubdomainChange} className="bg-transparent text-sm font-semibold focus:outline-none w-full" />
                          <span className="text-[10px] font-bold text-stone-400 tracking-widest">.GS.IN</span>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 ml-4">MAIN HEADLINE</label>
                        <input value={enhancedData.heroTitle} onChange={(e) => setEnhancedData({...enhancedData, heroTitle: e.target.value})} className="w-full bg-white border border-stone-200 rounded-[24px] px-6 py-4 text-sm font-semibold focus:outline-none focus:border-stone-900 shadow-sm transition-all" />
                      </div>

                      <div className="space-y-2">
                        <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 ml-4">HERO DESCRIPTION</label>
                        <textarea rows={3} value={enhancedData.heroDescription} onChange={(e) => setEnhancedData({...enhancedData, heroDescription: e.target.value})} className="w-full bg-white border border-stone-200 rounded-[24px] p-6 text-sm font-medium focus:outline-none focus:border-stone-900 resize-none shadow-sm leading-relaxed transition-all" />
                      </div>
                    </div>

                    <div className="p-8 bg-stone-50 rounded-[40px] border border-stone-100 space-y-6">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 ml-4">ABOUT TITLE</label>
                          <input value={enhancedData.aboutHeadline} onChange={(e) => setEnhancedData({...enhancedData, aboutHeadline: e.target.value})} className="w-full bg-white border border-stone-200 rounded-[24px] px-6 py-4 text-sm font-semibold focus:outline-none focus:border-stone-900 shadow-sm transition-all" />
                        </div>
                        <div className="space-y-2">
                          <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 ml-4">TAGLINE</label>
                          <input value={enhancedData.tagline} onChange={(e) => setEnhancedData({...enhancedData, tagline: e.target.value})} className="w-full bg-white border border-stone-200 rounded-[24px] px-6 py-4 text-sm font-semibold focus:outline-none focus:border-stone-900 shadow-sm transition-all" />
                        </div>
                      </div>

                      <div className="space-y-2">
                        <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-stone-400 ml-4">BRAND STORY</label>
                        <textarea rows={4} value={enhancedData.aboutBody} onChange={(e) => setEnhancedData({...enhancedData, aboutBody: e.target.value})} className="w-full bg-white border border-stone-200 rounded-[24px] p-6 text-sm font-medium focus:outline-none focus:border-stone-900 resize-none shadow-sm leading-relaxed transition-all" />
                      </div>
                    </div>

                    {/* Stats Editor */}
                    <div className="p-6 bg-slate-50 rounded-[32px] border border-black/[0.02] space-y-4">
                      <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Trust Counters</label>
                      <div className="grid grid-cols-3 gap-2">
                        {enhancedData.stats.map((s, i) => (
                          <div key={i} className="flex flex-col gap-1.5 p-3 rounded-2xl bg-white border border-black/[0.03] shadow-sm">
                            <input 
                              value={s.value} 
                              onChange={(e) => {
                                const newStats = [...enhancedData.stats];
                                newStats[i].value = e.target.value;
                                setEnhancedData({...enhancedData, stats: newStats});
                              }}
                              className="bg-transparent text-xs font-bold text-orange-600 focus:outline-none"
                            />
                            <input 
                              value={s.label} 
                              onChange={(e) => {
                                const newStats = [...enhancedData.stats];
                                newStats[i].label = e.target.value;
                                setEnhancedData({...enhancedData, stats: newStats});
                              }}
                              className="bg-transparent text-[8px] font-bold text-slate-400 uppercase tracking-wider focus:outline-none"
                            />
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="p-6 bg-slate-50 rounded-[32px] border border-black/[0.02] flex items-center justify-between">
                      <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Visual Theme</label>
                      <div className="flex gap-2.5">
                         {['orange', 'blue', 'sage', 'purple'].map(c => (
                           <button 
                            key={c} onClick={() => setTheme(c)}
                            className={`w-10 h-10 rounded-2xl border-2 transition-all ${theme === c ? 'border-slate-900 scale-110 shadow-lg' : 'border-transparent opacity-60 hover:opacity-100 hover:scale-105'}`}
                            style={{ backgroundColor: c === 'orange' ? '#ea580c' : c === 'blue' ? '#2563eb' : c === 'sage' ? '#047857' : '#9333ea' }}
                           />
                         ))}
                      </div>
                    </div>
                  </div>

                  {subdomainError && (
                    <div className="p-4 bg-rose-50 border border-rose-100 rounded-2xl text-[11px] font-bold text-rose-600 flex items-center gap-2 mt-4 animate-shake">
                      <ShieldAlert size={14} /> {subdomainError}
                    </div>
                  )}

                    <button 
                      onClick={handlePublish} disabled={loading || !subdomain}
                      className="w-full group relative flex items-center justify-center gap-3 py-4 rounded-2xl bg-orange-600 text-white font-bold text-sm shadow-xl shadow-orange-600/20 hover:bg-orange-700 transition-all active:scale-[0.98] disabled:bg-slate-100 disabled:text-slate-400 disabled:shadow-none overflow-hidden mt-8"
                    >
                      {loading ? (
                        <>
                          <Loader2 size={18} className="animate-spin" />
                          <span>Publishing Your Business...</span>
                        </>
                      ) : (
                        <>
                          <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/10 to-white/0 -translate-x-full group-hover:translate-x-full transition-transform duration-1000" />
                          <Globe size={18} />
                          <span>Launch Website Now</span>
                        </>
                      )}
                    </button>
                    {subdomainError && <p className="mt-3 text-[10px] text-center font-bold text-red-500 uppercase tracking-widest">{subdomainError}</p>}
                </motion.div>
              )}

              {/* SCREEN 5: Success & Share */}
              {successData && (
                <motion.div 
                  key="s5" initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} 
                  className="text-center py-10 space-y-8"
                >
                  <div className="w-20 h-20 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-6">
                    <CheckCircle className="text-emerald-600" size={40} />
                  </div>
                  
                  <div>
                    <h2 className="text-2xl font-black text-slate-900 tracking-tight">Your Website is LIVE!</h2>
                    <p className="mt-2 text-sm text-slate-400">Congratulations! Your business now has a professional home on the internet.</p>
                  </div>

                  <div className="p-6 bg-slate-50 border border-black/5 rounded-[32px] space-y-4">
                     <div className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Official Link</div>
                     <div className="text-sm font-bold text-slate-900 break-all bg-white p-4 rounded-2xl border border-black/5">
                        {successData.url}
                     </div>
                     <a 
                      href={successData.url} target="_blank"
                      className="w-full py-4 rounded-2xl bg-orange-600 text-white font-bold flex items-center justify-center gap-2 shadow-xl hover:bg-orange-700 transition-all"
                     >
                       Visit Your Site <ExternalLink size={16} />
                     </a>
                  </div>

                  <div className="pt-4">
                     <button 
                      onClick={() => window.location.reload()}
                      className="text-xs font-bold text-slate-400 hover:text-slate-900 transition"
                     >
                        Create Another Website
                     </button>
                  </div>
                </motion.div>
              )}

            </AnimatePresence>
          </div>

          <div className="mt-auto px-10 py-6 border-t border-black/[0.03] flex items-center justify-between shrink-0 bg-slate-50/50">
             <div className="flex items-center gap-2 text-[10px] font-bold text-slate-400">
                <ShieldCheck size={12} className="text-emerald-500" /> SSL Secured
             </div>
             <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Powered by Geetanjali Softwares</span>
          </div>

        </div>

        {/* RIGHT SIDE: Live Preview Workspace */}
        <div className="hidden lg:flex lg:w-7/12 h-full bg-slate-100 rounded-[32px] sm:rounded-[40px] border border-black/[0.03] p-8 flex-col overflow-hidden relative shadow-inner">
          
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <div className="flex gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-slate-200" />
                <div className="w-2.5 h-2.5 rounded-full bg-slate-200" />
                <div className="w-2.5 h-2.5 rounded-full bg-slate-200" />
              </div>
              <div className="px-6 py-2.5 rounded-2xl bg-white/60 backdrop-blur-md border border-white text-[10px] font-bold text-slate-400 shadow-sm min-w-[280px]">
                {typeof window !== 'undefined' && window.location.hostname.includes('localhost') 
                  ? `http://${subdomain || 'my-business'}.localhost:3000`
                  : `https://${subdomain || 'my-business'}.geetanjalisoftwares.in`}
              </div>
            </div>

            <div className="flex bg-white/50 backdrop-blur-md p-1.5 rounded-2xl border border-white shadow-sm">
               <button onClick={() => setPreviewMode('desktop')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 text-[10px] font-bold ${previewMode === 'desktop' ? 'bg-white text-orange-600 shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}><Tv size={14} /> Desktop</button>
               <button onClick={() => setPreviewMode('mobile')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 text-[10px] font-bold ${previewMode === 'mobile' ? 'bg-white text-orange-600 shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}><Smartphone size={14} /> Mobile</button>
            </div>
          </div>

          <div className="flex-grow flex items-center justify-center overflow-hidden">
            <motion.div 
              layout transition={{ type: 'spring', damping: 25, stiffness: 120 }}
              className={`bg-white shadow-2xl overflow-hidden relative ${previewMode === 'mobile' ? 'w-[320px] h-[600px] border-[10px] border-slate-900 rounded-[40px]' : 'w-full h-full rounded-2xl border border-black/5'}`}
            >
              <iframe 
                srcDoc={generatePreviewHTML()} 
                title="Preview" 
                className="w-full h-full border-0"
              />
            </motion.div>
          </div>

        </div>

      </main>

    </div>
  );
}
